### PR TITLE
[ Do not merge ]LD-8 | Unicode Usernames

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description 

Add validation for special characters usernames

## Test 
- Sign up  like a student
- Sign in,edit profile and enroll in a course
- Like staff generate a check out profile information 

# Reviewers
- [ ] @felipemontoya

### CODE REVIEW

**Comment by felipemontoya** [comment]
@andrey-canon could you please remove the changes that are only meant to fix pep8 and pylint, but that have no other use in the context of the PR.

Also, we based this feature on the work done at edraak a long time ago. Since then and precisely from ficus to ginkgo, this [PR](https://github.com/edx/edx-platform/pull/14729) was merged adding support for this. I want to test if we can use that pr instead of this code to get the same functionality.
Perhaps @jfavellar90 wants to be in the loop for this. We could do the changes in stage and decide after we see it in action.

**Comment by andrey-canon** [comment]
@felipemontoya  the issue is fixed in branch ednx/ginkgo+edunext therefore this PR is not necessary,  to test  you only have to add FEATURES['ENABLE_UNICODE_USERNAME'] = True in settings

**Comment by felipemontoya** [comment]
Awesome! Then we need to make sure this feature is turned on, and we can remove completely LD-8 for future migrations :+1:

@jfavellar90 fyi

**Comment by OmarIthawi** [comment]
@andrey-canon @felipemontoya Both `Edraak`'s (being used in [eduNEXT's platform](https://github.com/eduNEXT/edunext-platform)) and the upstream PR (https://github.com/edx/edx-platform/pull/14729) has the same effect. I'd suggest sticking with the upstream new one (https://github.com/edx/edx-platform/pull/14729).

Because there are anticipated changes in Django 1.11 and Django 2.0 which introduces Unicode name support AFAIK.

There's a caveat, you'd have to undo the Edraaks changes first.

**Comment by felipemontoya** [comment]
Hey @OmarIthawi, you are correct, that is what the [Do not merge is all about]. For this migration we have decided to go with the upstream version. Which is good, one less thing to worry about :joy:

**Comment by felipemontoya** [comment]
Yes. This was superseeded by LC-V2 which is now under review as well

**Pull request closed without merging**
