### PR TITLE
fix: use github version of py2neo instead of PyPI

### PR DESCRIPTION
**Pull request by magajh**
Errors during the build:

py2neo
`ERROR: Could not find a version that satisfies the requirement py2neo==3.1.2 (from -r requirements/edx/testing.txt (line 211)) (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1)
ERROR: No matching distribution found for py2neo==3.1.2 (from -r requirements/edx/testing.txt (line 211))`

**Changes**

- Cherry-pick of this [commit](https://github.com/edx/edx-platform/commit/41b01c07eb10982589da6b6e55f70ba36d592d68#diff-94403e312c40bceb86487dcf9d3c34c45bc869c40190b74d335fd1812a7c2533), since the version of [Py2neo](https://pypi.org/project/py2neo/#history) the platform depends on, has been removed from PyPI. 
- Updated the .txt files according to this https://github.com/edx/edx-platform/pull/27186/commits/6230d6b34a02253dc4dc75467b1f66652401008a

### CODE REVIEW

**Comment by morenol** [comment]
@magajh  Do we need to run make upgrade in order to update the .txt files, right?

**Comment by magajh** [comment]
@morenol yes that's right. I'm having problems right now running make upgrade

**Comment by morenol** [comment]
@magajh maybe we can try with this  https://github.com/edx/edx-platform/pull/27186/commits/6230d6b34a02253dc4dc75467b1f66652401008a

**Comment by magajh** [comment]
@morenol It worked. Thank you!

**Review by morenol — APPROVED** [review]

**Pull request merged**
