### PR TITLE
Simple add code for validate password reset values

### PR DESCRIPTION
**Pull request by Bound3R**
Check if form is invalid then show an error to the user.
This issue has referred in [EDNX-182](https://edunext.atlassian.net/browse/EDNX-182).

### CODE REVIEW

**Comment by felipemontoya** [comment]
We will not have to port this to ficus, so I will leave it test less for now.

**Comment by felipemontoya** [comment]
@Bound3R do you have a link to the PR where they changed this upstream?

**Comment by Bound3R** [comment]
@felipemontoya yeah [Show error message on password reset if provided passwords does not m…
](https://github.com/edx/edx-platform/commit/3f21b0718fb25303f2a810410bd69c8e77d06bc9)

**Comment by felipemontoya** [comment]
I noticed this PR has a very old base. Can you please rebase this to the latests master?

**Comment by Bound3R** [comment]
@felipemontoya Ready :+1:

**Comment by felipemontoya** [comment]
:+1:

**Pull request merged**
