### PR TITLE
Adding MicrositeMiddleware for studio app JFI-4

### PR DESCRIPTION
**Pull request by cocococosti**

### CODE REVIEW

**Comment by jfavellar90** [comment]
@cocococosti please move this to eox-tenant

**Comment by cocococosti** [comment]
I thought eox tenant didn't have support for cms. Just to be sure, I should add this to the lms settings at eox tenant? @jfavellar90

**Comment by morenol** [comment]
@cocococosti I think that you should add this to the cms settings at eox tenant. 

The eox-tenant right now is not capable of adding multitenancy to cms, but it can be used to do the same thing that is being done in this PR

**Comment by cocococosti** [comment]
ok, I'll do that @morenol

**Pull request closed without merging**
