### PR TITLE
Fixed printing syntax error

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
This PR fixes the printing error -in python 3.5- in problem_with_hint.yaml that affected the creation of problems with adaptive hints

### CODE REVIEW

**Comment by felipemontoya** [comment]
@mariajgrimaldi althought this looks good to me, I do have a few questions.

This is only a template that outputs some example code right? Is the example code meant to be run in the codejailed code?

@ericfab179 are we running the codejail still on python2.7?

**Comment by felipemontoya** [comment]
@mariajgrimaldi if we merge this, it would be important to also make an OSPR request with the same changes

**Comment by mariajgrimaldi** [comment]
Hey, @felipemontoya 

1. This is only a template that outputs some example code right?
     Yes, that's what I know.

2. Is the example code meant to be run in the codejailed code?
Yes. The code is executed using this method:
https://github.com/eduNEXT/edunext-platform/blob/59a39c67ca1e886e4ec8c9f6e669ac4ba58cef19/common/lib/capa/capa/capa_problem.py#L916

Defined here:
https://github.com/eduNEXT/edunext-platform/blob/59a39c67ca1e886e4ec8c9f6e669ac4ba58cef19/common/lib/capa/capa/safe_exec/safe_exec.py#L82

And that method uses `safe_exec` from `codejail`. Is that what you meant?

**Comment by felipemontoya** [comment]
Then it is more important than ever to know if codejail is running on python2.7 or 3.5. cc @jfavellar90 and @ericfab179

**Comment by mariajgrimaldi** [comment]
Hey @felipemontoya I added `sys.version` to the _hint_ and this was what I got:
Screenshot from 2020-12-10 09-33-27

**Comment by felipemontoya** [comment]
Yep. I talked to @jfavellar90 and he confirmed that we are using 3.5 but we will be moving to 2.7 before the migration

**Comment by mariajgrimaldi** [comment]
> Yep. I talked to @jfavellar90 and he confirmed that we are using 3.5 but we will be moving to 2.7 before the migration

should I close this then?

**Pull request closed without merging**
