### PR TITLE
Updating xblock poll version to 1.8.4

### PR DESCRIPTION
**Pull request by jfavellar90**
Updating the xblock-poll to support correctly the download of poll and survey results through the button "download results to csv". Already tested in stage

@felipemontoya 
@Alec4r 
@diegomillan 
@Squirrel18

### CODE REVIEW

**Comment by Squirrel18** [comment]
Is this required to fix some broken behavior?. Upstream is still using 1.5.1. do we need to upgrade this in the next migrations? @jfavellar90

**Comment by jfavellar90** [comment]
@Squirrel18 the motivation behind this PR is [here](https://3.basecamp.com/3966315/buckets/8050706/todos/1647631403). If this is not included in upstream yet, we can create a PR to get these changes merged ASAP. It's sure we have to support this for Ironwood

**Comment by Squirrel18** [comment]
Ok. @jfavellar90

**Comment by jfavellar90** [comment]
Failing tests are unrelated to the applied change so I proceed with the merge

**Pull request merged**
