### PR TITLE
Adding commits f9689aa to fe5c627 from upstream

### PR DESCRIPTION
**Pull request by cocococosti**
Applying patch to update our branch with upstream open-release/ironwood.master

### CODE REVIEW

**Comment by morenol** [comment]
What about these commits:
https://github.com/eduNEXT/edx-platform/commit/b57df7ad720d685f52762f6cd2019feedfb1e2f8
https://github.com/eduNEXT/edx-platform/commit/25e929f169394533ccb90fa908febe36646d497c
https://github.com/eduNEXT/edx-platform/commit/b33db2c548a1a530510d785f7659c78783a187fa
https://github.com/eduNEXT/edx-platform/commit/441d6384eef5ed0b62e936a7d85958d10e43d92e
?

**Comment by cocococosti** [comment]
Sorry I just saw this commit 34149c7a37677ec5d90cae97c0ba29ea786fc018 and thought the next ones were the only new ones. I'll fix it.

**Comment by jfavellar90** [comment]
@cocococosti did not understand your last comment

**Comment by cocococosti** [comment]
@jfavellar90 asked me to do it as a patch so we have a cleaner history. The commits added here are the ones that go from f9689aa to fe5c627. 34149c7 is the commit before f9689aa, and the last one from upstream that we had in our branch. @morenol

**Comment by jfavellar90** [comment]
@morenol @cocococosti I don't think we'll have many changes from upstream on the ironwood release branch, so to keep it simple we can proceed with this merge, given the tests are passing (these changes are unrelated with our custom changes)

**Pull request merged**
