### PR TITLE
Bumping version of eox-core plugin to 0.12.0

### PR DESCRIPTION
**Pull request by diegomillan**
Bumping version of eox-core plugin to 0.11.0 which includes new business logic to access APIs
@felipemontoya

### CODE REVIEW

**Comment by jfavellar90** [comment]
@felipemontoya @diegomillan are we still working on the migration branch ednx/hawthorn+edunext?

**Comment by diegomillan** [comment]
I think so @jfavellar90 @felipemontoya

**Comment by jfavellar90** [comment]
@diegomillan I suppose your changes are not the reason why test went to the recalcada

**Comment by diegomillan** [comment]
Im debugging now , could be a settings problem @jfavellar90

**Comment by jfavellar90** [comment]
@felipemontoya a bump on LLPA of eox-core is required?

**Comment by felipemontoya** [comment]
Test DB continues to fail, but we have tested both locally and in circle over ssh and it passes. I suppose this is related to the cache

**Pull request merged**
