### PR TITLE
JU-9: Implementing strategy to make problem_responses_csv instructor report…

### PR DESCRIPTION
**Pull request by MaferMazu**
## Description

This pr makes the query faster when a problem report is generated.

- [Jira](https://edunext.atlassian.net/browse/PS2021-1174?atlOrigin=eyJpIjoiYzI4NDU5ODlkNzY2NDEyNDhjNzlmZGQzODZkNzA1MTQiLCJwIjoiaiJ9)
- [Juniper version](https://github.com/eduNEXT/edunext-platform/pull/445)
- [Documentation](https://docs.google.com/document/d/1wCxCeqojOizVbF0JJCwfCv75bR1XTnjTdVkzZv5mQ6U/edit)

## How to test

To test go to the lms to a course and in the instructor and data download tab select "create a report of problem ..."
Example: https://bux-staging-bracu-ac-bd.le.edunextstage.net/courses/course-v1:buX+ARC101+2021_Spring/instructor#view-data_download
Screenshot from 2021-12-08 18-39-13

## Result of my tests

- https://bux-staging-bracu-ac-bd.le.edunextstage.net/courses/course-v1:buX+ARC111+2020_Fall/course/

53 Students

Without this PR :
Screenshot from 2021-12-08 17-13-43
With PR:
Screenshot from 2021-12-08 18-13-29

Without pr 4560 ms and with pr 4174
Generates an improvement of 8.4%

- https://bux-staging-bracu-ac-bd.le.edunextstage.net/courses/course-v1:buX+ARC101+2021_Spring/instructor#view-course_info

21 Students

Without PR:
Screenshot from 2021-12-08 17-27-37

With PR:
Screenshot from 2021-12-08 18-19-20

Without pr 4607 ms and with pr 3570
Generates an improvement of 22.5%

- https://openedx-edunext-co.le.edunextstage.net/courses/course-v1:SEGES+AARS2.0+2016_1/instructor#view-course_info

462 Students

Without PR:
Screenshot from 2021-12-08 17-29-16

With PR:
Screenshot from 2021-12-08 18-21-10

Without pr 1840 ms and with pr: 1385 ms
Generates an improvement of 24.7%

### CODE REVIEW

**Comment by MaferMazu** [comment]
Courses with more enrollments (without pr):

- https://scientiagenus-buap-mx.le.edunextstage.net/courses/course-v1:buap+C101+2020_S2/instructor 
57253 Enrollments but in stage lilac have 38

Screenshot from 2021-12-09 13-13-36

- https://lms-academia-pt.le.edunextstage.net/courses/course-v1:academiadigital+EV+acao1/instructor

13691 enrollments

Screenshot from 2021-12-09 13-26-08

- https://eacademy-spea-ae.le.edunextstage.net/courses/course-v1:SharjahVirtualAcademy+edu124+2020/instructor#view-course_info

13094 enrollments

Screenshot from 2021-12-09 13-32-57

## Conclusion

All queries take seconds maybe it is better not to merge this, the change is not very big.

**Comment by mariajgrimaldi** [comment]
can you add the improvement % in the latest comment? @MaferMazu

**Comment by MaferMazu** [comment]
I did not try it with the pr because they told me in the daily that if without the pr it took less than a minute it was not worth keeping ju-9, although I can try with the pr if necessary but I don't think it is more than 30% of improvement, it must be taken into account that everything is in ms, so if something takes 4sec the improvement would be that it last about 3sec.

cc @mariajgrimaldi

**Comment by MoisesGSalas** [comment]
I'm in favor of closing this PR. The improvements that come from upstream seem good enough.

**Pull request closed without merging**
