### PR TITLE
Making the regex that gets the index courses more secure GI-13

### PR DESCRIPTION
**Pull request by cocococosti**

### CODE REVIEW

**Comment by jfavellar90** [comment]
@cocococosti did you test this one in dev?

**Comment by cocococosti** [comment]
I never knew how. I checked the platform was working correctly but couldn't replicate the error that needed this solution. Big fail on my part, sorry. I'm on it now. @jfavellar90

**Comment by cocococosti** [comment]
Also, is there a unit test for this? I looked for it but couldn't find any.

**Comment by jfavellar90** [comment]
@cocococosti please read the description of the feature and let me know if it's clear for you, if not I can explain you what is this about

**Comment by cocococosti** [comment]
Tested in dev and works correctly. Created two microsites, each with different organizations starting with the same letters: EXA and EXAMPLE. Created a course for each organization. Before the change both courses would show up at the EXA microsite, after the change each microsite shows its own course only. @jfavellar90

**Comment by jfavellar90** [comment]
@cocococosti cool, it's OK from my side

**Pull request merged**
