### PR TITLE
HA-20 | fix error with the model admin of course enrollment

### PR DESCRIPTION
**Pull request by jfavellar90**
Fix error with the model admin of course enrollment, which was generating 500 error when trying to update a course enrollment record on django admin

@felipemontoya 
@diegomillan

### CODE REVIEW

**Comment by felipemontoya** [comment]
I was looking at master, and could not see this change.

https://github.com/edx/edx-platform/blob/master/common/djangoapps/student/admin.py

Is this also failing for master?

**Comment by jfavellar90** [comment]
@felipemontoya I know @Alec4r had a link to the PR fixing this issue, maybe is still pending to merge

**Comment by felipemontoya** [comment]
@Alec4r do you have the link to the original PR?

**Comment by Alec4r** [comment]
@felipemontoya not, i not have the original link of the PR , the pr solved a similar theme but in another model if I remember correctly.

**Pull request merged**
