### PR TITLE
Making edx-notes-api feature microsite aware

### PR DESCRIPTION
**Pull request by jfavellar90**

### CODE REVIEW

**Comment by jfavellar90** [comment]
@felipemontoya

**Comment by felipemontoya** [comment]
I assume we need this, right?

**Comment by jfavellar90** [comment]
Yes, it allows to enable or disable the notes service per microsite in lms. For cms it's always activated

**Comment by felipemontoya** [comment]
And the default is enabled or disabled?

**Comment by jfavellar90** [comment]
In lms by default is disabled, in cms by default is enabled

**Comment by felipemontoya** [comment]
:+1:

**Pull request merged**
