### PR TITLE
Removing eox-tenant signals connection

### PR DESCRIPTION
**Pull request by diegomillan**
This PR removes signals connection from the platform. We will connect our receivers relying on [eox-tenant#27](https://github.com/eduNEXT/eox-tenant/pull/27)

@felipemontoya 
@jfavellar90 
@Squirrel18

### CODE REVIEW

**Comment by jfavellar90** [comment]
@diegomillan now signals are initilized on the plugin app config?

**Comment by diegomillan** [comment]
Exactly @jfavellar90

**Comment by diegomillan** [comment]
Yes, I will take care of those details @felipemontoya

**Comment by diegomillan** [comment]
Feedback applied @felipemontoya

**Pull request merged**
