### PR TITLE
fix: Set RTL text in editor of xblock problem.

### PR DESCRIPTION
**Pull request by andrey-canon**
## Description

Nelp migration feature from https://github.com/eduNEXT/edx-platform/pull/257

### CODE REVIEW

**Comment by johanv26** [comment]
@andrey-canon for the next cherry picks is ideally to show the coautor or the reference for the original commit.

**Comment by andrey-canon** [comment]
> @andrey-canon I think that for the next cherry picks is ideally to show the coautor in the commit or the reference for the original commit.

This is not a cherry pick

**Comment by johanv26** [comment]
So why is not a cherry-pick if it is the same change?
This PR
https://github.com/eduNEXT/edunext-platform/pull/669/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32
Previous PR
https://github.com/eduNEXT/edx-platform/pull/257/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32

**Comment by andrey-canon** [comment]
> So why is not a cherry-pick if it is the same change? This PR https://github.com/eduNEXT/edunext-platform/pull/669/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32 Previous PR https://github.com/eduNEXT/edx-platform/pull/257/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32

Because a cherry pick requires to run the cherry pick command https://git-scm.com/docs/git-cherry-pick, this is just a copy of the same modification

**Comment by johanv26** [comment]
> > So why is not a cherry-pick if it is the same change? This PR https://github.com/eduNEXT/edunext-platform/pull/669/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32 Previous PR https://github.com/eduNEXT/edx-platform/pull/257/files#diff-fed66e56343906076881d7e1ff6c58b76e9ed8797877d2e8f0f5d85322a0e5ccR32
> 
> Because a cherry pick requires to run the cherry pick command https://git-scm.com/docs/git-cherry-pick, this is just a copy of the same modification

Yes but is only if it is possible to use the cherry-pick we can use it for future commits.

**Review by johanv26 — APPROVED** [review]

**Pull request merged**
