### PR TITLE
Support ticket #4213 - Issue with video player.

### PR DESCRIPTION
**Pull request by Squirrel18**
## Description:

Adds #19645 openedx upstream PR fix, about video speed issue.

## Reviewers:

 - [x] @diegomillan 
 - [ ] @jfavellar90 
 - [ ] @felipemontoya

### CODE REVIEW

**Comment by Squirrel18** [comment]
@diegomillan Could you please merge this PR, since the only failing test is Test_db.py.

**Comment by diegomillan** [comment]
Yes, I'm still working on those tests. So, let's merge this. @Squirrel18

**Comment by felipemontoya** [comment]
In this PR we are still missing some context.

Why did we need this change?
Which support case reported it?
Has this been fixed in master and ported back to our branch?
Has an OSPR been opened?
Are we willing to maintain this change for the foreseeable future with our own effort? 

Bottom line: it is not only a matter of making things work, how we will support this in the future is at least (if no more) important than the change itself

**Comment by felipemontoya** [comment]
I just saw that this was changed as well in master, so this means it was a port to our branch.

Still, please fill in the context and make sure to make a link to the original PR (https://github.com/edx/edx-platform/pull/19645) in the PR cover letter

**Comment by felipemontoya** [comment]
@Squirrel18 this is no joke. It is an exercise. Make sure to update this PR and include a real cover letter

**Comment by felipemontoya** [comment]
> @Squirrel18 this is no joke. It is an exercise. Make sure to update this PR and include a real cover letter

sorry, I reloaded and did not see any changes. Reloaded again, and now I saw the changes.

**Comment by Squirrel18** [comment]
@felipemontoya I know it is not a joke, so far i see your comments.

**Pull request merged**
