### PR TITLE
Adding a lang selector in the footer of studio

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Comment by morenol** [comment]
Since this is a change on the html template, maybe this could be handled through the theme or anything else we will use for the theming stuffs

**Comment by jfavellar90** [comment]
@morenol I think we can keep this but leaving a note on the migration Excel file about the possible migration to eox-theming

**Comment by morenol** [comment]
I mean, this change can be done without eox-theming. We just need to add the template to the comprehensive theme

**Comment by morenol** [comment]
@jfavellar90 @felipemontoya How we will proceed?

**Pull request merged**
