### PR TITLE
feat: add api MFE configuration

### PR DESCRIPTION
**Pull request by dcoa**
# feat: add api MFE configuration

## Description

This PR is a backport of all the commits related to MFE API configuration. 

## Supporting information
The related PR are:

- https://github.com/openedx/edx-platform/pull/30830
- https://github.com/openedx/edx-platform/pull/30473

## Testing instructions

Please, follow the instructions here https://github.com/openedx/edx-platform/pull/30473

## Additional information 
[JIRA CARD](https://edunext.atlassian.net/browse/DS-557)

### CODE REVIEW

**Comment by MaferMazu** [comment]
Hello Diana, thanks for this, but I wonder if we want this PR. The acceptance criteria for that Jira card are more about having a "productive" branch about CSS variables in the frontend platform and learning mfe and having a strain published around your work of CSS variables.

@santiagosuarezedunext @Alec4r, do you know if someone on the team uses MFE in Nutmeg and probably wants this?

The backport is okay, and these changes won't break things, but as I said, I am not so sure we want this because, as eduNEXT, we are trying these things in Olmo.

**Comment by dcoa** [comment]
@MaferMazu let me explain a little bit more the context:

1. Point 1 of the acceptance criteria talks about nuez and olmo releases.
2. The third acceptance criteria requests to describe how to have an environment with CSS variables, which is why we need this backport.

**Comment by dcoa** [comment]
Understanding that we are gonna use this in Olmo, I proceed to close this PR.

**Review by MaferMazu — APPROVED** [review]
Looks good to me

**Review by JuanDavidBuitrago — APPROVED** [review]
It looks good, but I wonder how can we switch between have or no have MFE configurations, as we know, MFE is not mandatory in Nutmeg/Nuez

If this is not a problem, go ahead!

**Comment by dcoa** [comment]
It's all about configurations to enable the API you should have `ENABLE_MFE_CONFIG_API` in true and disable or enable MFE's with the django flags.

**Comment by JuanDavidBuitrago** [comment]
Thanks for the clarification @dcoa.

**Pull request merged**
